# Site settings
title: British Airways California
description: >
  What better way to explore this vibrant state than by embarking on the all-American road trip. With flights from British Airways landing you in comfort to five of California’s most buzzing cities, you’ll be set to hop into your chosen vehicle and go exploring.
baseurl: "/britishairwayscalifornia" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]
